plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "cs"]
exclude_from_localizations: ["assets"]
assetsPath: "/assets"
baseurl: "/website"

sass:
  implementation: sass-embedded

collections:
