plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "cs"]
exclude_from_localizations: ["assets"]
assetsPath: "/website/assets"
baseurl: ""

sass:
  implementation: sass-embedded

collections:
